# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-02 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shall',
            name='goldTotal',
            field=models.IntegerField(default=0, verbose_name='\u9ec4\u91d1\u67f1\u4e2a\u6570'),
        ),
        migrations.AddField(
            model_name='shalldetail',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u989c\u8272'),
        ),
        migrations.AddField(
            model_name='szall',
            name='goldTotal',
            field=models.IntegerField(default=0, verbose_name='\u9ec4\u91d1\u67f1\u4e2a\u6570'),
        ),
        migrations.AddField(
            model_name='szalldetail',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u989c\u8272'),
        ),
    ]
